---
- hosts: localhost
  connection: local
  tasks:
    - name: Install Chocolatey packages
      win_chocolatey:
        name:
        - vscode
        - git
        - nvm
        - docker-desktop
        - chromium
        - slack
        - dropbox
        state: latest